name: AARCH64 Packing

on: workflow_call


jobs:
  linux-packing:
    name: AARCH64 Packing
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'   # 为所有步骤设置时区

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: jadehh/jade_tools
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0           # 获取完整的历史记录，而不只是最新提交
          fetch-tags: true         # 显式告诉 Action 去获取所有标签

      - name: Extract Version from Tag
        id: get_version
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "tag_name=${tag}" >> $GITHUB_OUTPUT
          # 提取仓库名称（去掉 -v 及后面的版本号）
          repo_name=$(echo "${tag}" | sed 's/-v[0-9].*//')
          echo "repo_name=${repo_name}" >> $GITHUB_OUTPUT
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Dynamic Library Jade Tools Slim  for AARCH64
        run: |
          echo "Build Dynamic Library Jade Tools Slim  for AARCH64 构建开始时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"
          docker run  --rm --platform linux/arm64  --name build_shared -u $(id -u):$(id -g) -v  ${{ github.workspace }}:/app  \
                      -w /app ghcr.io/jadehh/jade_tools:1.0.2-slim-devel-ubuntu18.04 bash -c "
              mkdir -p build-jade-tools-slim-aarch64 && cd build-jade-tools-slim-aarch64 && \
              cmake ..  \
                -D CMAKE_BUILD_TYPE=Release \
                -D CMAKE_INSTALL_PREFIX=../jade_tools-slim-aarch64 \
                -D USE_OPENCV_4=OFF \
                -D SQLITE3_DIR=/usr/include \
                -D OPENSSL_DIR=/usr/include \
                -D BREAKPAD_DIR=/usr/local/include/breakpad \
                -D SPDLOG_DIR=/usr/local/include/spdlog \
                -D OPENCV_DIR=/usr/local/opencv  \
                -D MODBUS_DIR=/usr/include \
                -D PUGIXML_DIR=/usr/include && \
              make -j $(nproc) && make install  && rm -r ../build-jade-tools-slim-aarch64"
          echo "Build Dynamic Library Jade Tools Slim  for AARCH64 构建结束时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"        

      - name: Build Dynamic Library Jade Tools Cpu  for AARCH64
        run: |
          echo "Build Dynamic Library Jade Tools Cpu  for AARCH64 构建开始时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"
          docker run  --rm --platform linux/arm64  --name build_shared -u $(id -u):$(id -g) -v  ${{ github.workspace }}:/app  \
                      -w /app ghcr.io/jadehh/jade_tools:1.0.3-cpu-devel-ubuntu18.04 bash -c "
              mkdir -p build-jade-tools-cpu-aarch64 && cd build-jade-tools-cpu-aarch64 && \
              cmake ..  \
                -D CMAKE_BUILD_TYPE=Release \
                -D CMAKE_INSTALL_PREFIX=../jade_tools-cpu-aarch64 \
                -D USE_OPENCV_4=ON \
                -D USE_OPENCV_CUDA=OFF \
                -D SQLITE3_DIR=/usr/include \
                -D OPENSSL_DIR=/usr/include \
                -D BREAKPAD_DIR=/usr/local/include/breakpad \
                -D SPDLOG_DIR=/usr/local/include/spdlog \
                -D OPENCV_DIR=/usr/local/opencv  \
                -D HASP_ADAPTER_DIR=/usr/local/include \
                -D MODBUS_DIR=/usr/include \
                -D PUGIXML_DIR=/usr/include && \
              make -j $(nproc) && make install  && rm -r ../build-jade-tools-cpu-aarch64"
          echo "Build Dynamic Library Jade Tools Cpu  for AARCH64 构建结束时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"

      - name: Build Dynamic Library Jade Tools CANN6  for AARCH64
        run: |
          echo "Build Dynamic Library Jade Tools CANN6  for AARCH64 构建开始时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"
          docker run  --rm --platform linux/arm64  --name build_shared -u $(id -u):$(id -g) -v  ${{ github.workspace }}:/app  \
                      -w /app ghcr.io/jadehh/jade_tools:1.0.4-cann6-ubuntu20.04 bash -c "
                mkdir -p build-jade-tools-cann6-aarch64 && cd build-jade-tools-cann6-aarch64 && \
                cmake ..  \
                -D CMAKE_BUILD_TYPE=Release \
                -D CMAKE_INSTALL_PREFIX=../jade_tools-cann6-aarch64 \
                -D USE_OPENCV_4=ON \
                -D USE_OPENCV_CUDA=OFF \
                -D SQLITE3_DIR=/usr/include \
                -D OPENSSL_DIR=/usr/include \
                -D BREAKPAD_DIR=/usr/local/include/breakpad \
                -D SPDLOG_DIR=/usr/local/include/spdlog \
                -D OPENCV_DIR=/usr/local/opencv  \
                -D HASP_ADAPTER_DIR=/usr/local/include  \
                -D ASCEND_DIR=/usr/local/Ascend/ascend-toolkit/latest \
                -D MODBUS_DIR=/usr/include \
                -D PUGIXML_DIR=/usr/include && \
                make -j $(nproc) && make install  && rm -r ../build-jade-tools-cann6-aarch64"
          echo "Build Dynamic Library Jade Tools CANN6  for AARCH64 构建结束时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"


      - name: Tar Jade Tools
        run: |
          # 压缩 slim 包
          tar -czvf ${{ steps.get_version.outputs.tag_name }}-slim-aarch64.tar.gz -C jade_tools-slim-aarch64 .
          tar -czvf ${{ steps.get_version.outputs.tag_name }}-runtime-slim-aarch64.tar.gz -C jade_tools-slim-aarch64/lib .
          md5sum ${{ steps.get_version.outputs.tag_name }}-runtime-slim-aarch64.tar.gz > ${{ steps.get_version.outputs.tag_name }}-runtime-slim-aarch64.tar.gz.md5
          # 压缩 cpu 包
          tar -czvf ${{ steps.get_version.outputs.tag_name }}-cpu-aarch64.tar.gz -C jade_tools-cpu-aarch64 .
          tar -czvf ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-aarch64.tar.gz -C jade_tools-cpu-aarch64/lib .
          md5sum ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-aarch64.tar.gz > ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-aarch64.tar.gz.md5
          # 压缩 cann6 包
          tar -czvf ${{ steps.get_version.outputs.tag_name }}-cann6-aarch64.tar.gz -C jade_tools-cann6-aarch64 .
          tar -czvf ${{ steps.get_version.outputs.tag_name }}-runtime-cann6-aarch64.tar.gz -C jade_tools-cann6-aarch64/lib .
          md5sum ${{ steps.get_version.outputs.tag_name }}-runtime-cann6-aarch64.tar.gz > ${{ steps.get_version.outputs.tag_name }}-runtime-cann6-aarch64.tar.gz.md5
     

      - name: Generate Linux Download Information
        run: |
          cmake -D OUTPUT_FILE=RELEASE_NOTES.md -P cmake/extractChangelog.cmake
          # jade tools slim runtime 信息
          file_slim="${{ steps.get_version.outputs.tag_name }}-runtime-slim-aarch64.tar.gz"
          md5_slim=$(cat "${file_slim}.md5" | awk '{print $1}')
          download_url_slim="https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file_slim"
          # jade tools cpu runtime 信息
          file_cpu="${{ steps.get_version.outputs.tag_name }}-runtime-cpu-aarch64.tar.gz"
          md5_cpu=$(cat "${file_cpu}.md5" | awk '{print $1}')
          download_url_cpu="https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file_cpu"
          # jade tools cann6 runtime 信息
          file_cann6="${{ steps.get_version.outputs.tag_name }}-runtime-cann6-aarch64.tar.gz"
          md5_cann6=$(cat "${file_cann6}.md5" | awk '{print $1}')
          download_url_cann6="https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file_cann6"
          # 生成 JSON 格式的下载信息
          cat > aarch64.json << JSONEOF
          {
          "platform": "aarch64",
          "tag_name": "${{ steps.get_version.outputs.tag_name }}",
          "packages": [
            {
              "name": "slim",
              "file": "${file_slim}",
              "md5": "${md5_slim}",
              "download_url": "${download_url_slim}"
            },
            {
              "name": "cpu",
              "file": "${file_cpu}",
              "md5": "${md5_cpu}",
              "download_url": "${download_url_cpu}"
            },
            {
              "name": "cann6",
              "file": "${file_cann6}",
              "md5": "${md5_cann6}",
              "download_url": "${download_url_cann6}"
            }
          ]
          }
          JSONEOF


      - name: Upload AARCH64 Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: "${{ steps.get_version.outputs.tag_name }}"
          body_path: "RELEASE_NOTES.md"
          files: |
            ${{ steps.get_version.outputs.tag_name }}-slim-aarch64.tar.gz
            ${{ steps.get_version.outputs.tag_name }}-cpu-aarch64.tar.gz
            ${{ steps.get_version.outputs.tag_name }}-cann6-aarch64.tar.gz
            ${{ steps.get_version.outputs.tag_name }}-runtime-slim-aarch64.tar.gz
            ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-aarch64.tar.gz
            ${{ steps.get_version.outputs.tag_name }}-runtime-cann6-aarch64.tar.gz
            aarch64.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}