name: Linux Packing

on: workflow_call


jobs:
  linux-packing:
    name: Linux Packing
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'   # 为所有步骤设置时区

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: jadehh/ContainerOCRService
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0           # 获取完整的历史记录，而不只是最新提交
          fetch-tags: true         # 显式告诉 Action 去获取所有标签

      - name: Extract Version from Tag
        id: get_version
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "tag_name=${tag}" >> $GITHUB_OUTPUT
          # 提取仓库名称（去掉 -v 及后面的版本号）
          repo_name=$(echo "${tag}" | sed 's/-v[0-9].*//')
          echo "repo_name=${repo_name}" >> $GITHUB_OUTPUT

      - name: Build Dynamic Library Container OCR Service for Linux
        run: |
          echo "Build Dynamic Library Container OCR Service for Linux 构建开始时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"
          docker run  --rm  --name duild -v ${PWD}:/app  -w /app ghcr.io/jadehh/container_ocr_service:1.0.0-ubuntu18.04 bash -c "
          mkdir -p build && cd build && \ 
          cmake ..  \
          -D CMAKE_BUILD_TYPE=Release \
          -D PUGIXML_DIR=/usr/include
          make -j $(nproc) container-ocr-service  && rm -r ../build"
          echo "Build Dynamic Library Container OCR Service for Linux 构建结束时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"

      - name: Generate Linux Download Information
        run: |
          # 如果不存在使用则新建
          cmake -D OUTPUT_FILE=RELEASE_NOTES.md -P cmake/extractChangelog.cmake
          cp output/Release/container-ocr-service ./
          file="container-ocr-service"
          md5sum "$file" > "$file".md5
          md5=$(cat "${file}".md5 | awk '{print $1}')
          download_url="https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file"
         
          # 生成 JSON 格式的下载信息
          cat > linux.json << JSONEOF
          {
          "platform": "linux",
          "tag_name": "${{ steps.get_version.outputs.tag_name }}",
          "packages": [
            {
              "name": "container-ocr-service",
              "file": "${file}",
              "md5": "${md5}",
              "download_url": "${download_url}"
            }
          ]
          }
          JSONEOF
          

      - name: Upload Linux Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: "${{ steps.get_version.outputs.tag_name }}"
          body_path: "RELEASE_NOTES.md"
          files: |
            container-ocr-service
            linux.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}