name: Windows Packing

on: workflow_call

jobs:
  windows-packing:
    name: Windows Packing
    runs-on: windows-latest
    env:
      TZ: 'Asia/Shanghai'
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: jadehh/ContainerOCRService
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0           # 获取完整的历史记录，而不只是最新提交
          fetch-tags: true         # 显式告诉 Action 去获取所有标签

      - name: Extract Version from Tag
        id: get_version
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/',''
          echo "tag_name=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          $repo_name = $tag -replace '-v\d+.*',''
          echo "repo_name=$repo_name" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "lib_name=lib$repo_name" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Build Dynamic Library ContainerOCRService for Windows With Docker
        shell: pwsh
        run: |
          echo "Build Dynamic Library ContainerOCRService for Windows 构建开始时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
          docker run --rm --name build -v ${PWD}:C:\app -w C:\app jadehh/container_ocr_service:1.0.0-windows2022 cmd /c "call ""C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"" x64 && pwsh -NoProfile -File C:\app\templates\build.ps1"
          echo "Build Dynamic Library ContainerOCRService for Windows 构建结束时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"

      - name: Generate Windows Download Information
        run: |
          cmake -D OUTPUT_FILE=RELEASE_NOTES.md -P cmake/extractChangelog.cmake
          cp output/Release/container-ocr-service.exe ./
          # container-ocr-service 信息
          $file= "container-ocr-service.exe"
          certutil -hashfile $file MD5 > $file.md5
          $md5 = Get-Content "$file.md5" | Select-String -Pattern '[0-9a-f]{32}' | ForEach-Object { $_.Matches.Value }
          $download_url = "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file"
          $json = @{
            platform = "windows"
            tag_name = "${{ steps.get_version.outputs.tag_name }}"
            packages = @(
              @{name="container-ocr-service"; file = $file; md5 = $md5; download_url = $download_url },
            )
          }
          $json | ConvertTo-Json -Depth 3 | Out-File -FilePath windows.json -Encoding utf8


      - name: Upload Windows Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: "${{ steps.get_version.outputs.tag_name }}"
          body_path: "RELEASE_NOTES.md"
          files: |
            container-ocr-service.exe
            windows.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}