name: Windows Packing

on: workflow_call

jobs:
  windows-packing:
    name: Windows Packing
    runs-on: windows-latest
    env:
      TZ: 'Asia/Shanghai'
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          repository: jadehh/jade_tools
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0           # 获取完整的历史记录，而不只是最新提交
          fetch-tags: true         # 显式告诉 Action 去获取所有标签

      - name: Extract Version from Tag
        id: get_version
        run: |
          $tag = $env:GITHUB_REF -replace 'refs/tags/',''
          echo "tag_name=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          $repo_name = $tag -replace '-v\d+.*',''
          echo "repo_name=$repo_name" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "lib_name=lib$repo_name" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Build Dynamic Library Jade Tools Slim for Windows With Docker
        shell: pwsh
        run: |
          echo "Build Dynamic Library Jade Tools Slim for Windows 构建开始时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
          docker run --rm --name build_shared -v ${PWD}:c:\app -w /app ghcr.io/jadehh/jade_tools:1.0.2-slim-windows2022 pwsh -Command "
            & C:\\scripts\\start-with-h-drive.cmd;
            vcpkg integrate remove;
            git config --global --add safe.directory C:/app/
            mkdir -Force build-jade-tools-slim-windows && cd build-jade-tools-slim-windows;
            `$commonArgs = @(
              '..',
              '-A', 'Win32',
              '-D','CMAKE_INSTALL_PREFIX=../jade_tools-slim-windows',
              '-D', 'USE_OPENCV_4=OFF',
              '-D', 'OPENCV_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'BREAKPAD_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'SPDLOG_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'SQLITE3_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'OPENSSL_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'MODBUS_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'PUGIXML_DIR=H:/SDKS/vcpkg/installed'
            );
            cmake `$commonArgs
            cmake --build . --config Release --target install;
            cd ../ && cmd /c 'rmdir /s /q build-jade-tools-slim-windows;'" 
            echo "Build Dynamic Library Jade Tools Slim for Windows 构建结束时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')";
          docker rmi ghcr.io/jadehh/jade_tools:1.0.2-slim-windows2022

      - name: Build Dynamic Library Jade Tools Cpu for Windows With Docker
        shell: pwsh
        run: |
          echo "Build Dynamic Library Jade Tools Cpu for Windows 构建开始时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
          docker run --rm --name build_shared -v ${PWD}:c:\app -w /app ghcr.io/jadehh/jade_tools:1.0.2-cpu-windows2022 pwsh -Command "
            & C:\\scripts\\start-with-h-drive.cmd;
            vcpkg integrate remove;
            git config --global --add safe.directory C:/app/
            mkdir -Force build-jade-tools-cpu-windows && cd build-jade-tools-cpu-windows;
            `$commonArgs = @(
              '..',
              '-A', 'x64',
              '-D','CMAKE_INSTALL_PREFIX=../jade_tools-cpu-windows',
              '-D', 'USE_OPENCV_4=ON',
              '-D', 'USE_OPENCV_CUDA=OFF',
              '-D', 'OPENCV_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'BREAKPAD_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'SPDLOG_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'SQLITE3_DIR=H:/SDKS/vcpkg/installed'
              '-D', 'HASP_ADAPTER_DIR=H:/SDKS/vcpkg/installed'
              '-D', 'OPENSSL_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'MODBUS_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'PUGIXML_DIR=H:/SDKS/vcpkg/installed'
            );
            cmake `$commonArgs
            cmake --build . --config Release --target install;
            cd ../ && cmd /c 'rmdir /s /q build-jade-tools-cpu-windows;'" 
            echo "Build Dynamic Library Jade Tools Cpu for Windows 构建结束时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')";
          docker rmi ghcr.io/jadehh/jade_tools:1.0.3-cpu-windows2022

      - name: Build Dynamic Library Jade Tools CUDA for Windows With Docker
        shell: pwsh
        run: |
          echo "Build Dynamic Library Jade Tools CUDA  for Windows 构建开始时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
          docker run --rm --name build_shared -v ${PWD}:c:\app -w /app ghcr.io/jadehh/jade_tools:1.0.3-cuda12-windows2022 pwsh -Command "
            & C:\\scripts\\start-with-h-drive.cmd;
            vcpkg integrate remove;
            git config --global --add safe.directory C:/app/
            mkdir -Force build-jade-tools-cuda-12-windows && cd build-jade-tools-cuda-12-windows;
            `$commonArgs = @(
              '..',
              '-A', 'x64',
              '-D','CMAKE_INSTALL_PREFIX=../jade_tools-cuda12-windows',
              '-D', 'USE_OPENCV_4=ON',
              '-D', 'OPENCV_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'BREAKPAD_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'SPDLOG_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'SQLITE3_DIR=H:/SDKS/vcpkg/installed'
              '-D', 'HASP_ADAPTER_DIR=H:/SDKS/vcpkg/installed'
              '-D', 'OPENSSL_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'MODBUS_DIR=H:/SDKS/vcpkg/installed',
              '-D', 'PUGIXML_DIR=H:/SDKS/vcpkg/installed'
             );
            cmake `$commonArgs
            cmake --build . --config Release --target install;
            cd ../ && cmd /c 'rmdir /s /q build-jade-tools-cuda-12-windows;'" 
          echo "Build Dynamic Library Jade Tools CUDA  for Windows 构建结束时间: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"

      - name: Zip File
        run: |
          # 压缩 slim 包
          7z a ${{ steps.get_version.outputs.tag_name }}-slim-windows.zip jade_tools-slim-windows/
          cd jade_tools-slim-windows/x86-windows/bin/ ; 7z a ${{ steps.get_version.outputs.tag_name }}-runtime-slim-windows.zip * ; mv ${{ steps.get_version.outputs.tag_name }}-runtime-slim-windows.zip ../../../; cd ../../../
          certutil -hashfile ${{ steps.get_version.outputs.tag_name }}-runtime-slim-windows.zip MD5 > ${{ steps.get_version.outputs.tag_name }}-runtime-slim-windows.zip.md5
          # 压缩 cpu 包
          7z a ${{ steps.get_version.outputs.tag_name }}-cpu-windows.zip jade_tools-cpu-windows/
          cd jade_tools-cpu-windows/x64-windows/bin/ ; 7z a ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-windows.zip * ; mv ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-windows.zip ../../../; cd ../../../
          certutil -hashfile ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-windows.zip MD5 > ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-windows.zip.md5
          # 压缩 cuda 包
          7z a ${{ steps.get_version.outputs.tag_name }}-cuda12-windows.zip jade_tools-cuda12-windows/
          cd jade_tools-cuda12-windows/x64-windows/bin/ ; 7z a ${{ steps.get_version.outputs.tag_name }}-runtime-cuda12-windows.zip * ; mv ${{ steps.get_version.outputs.tag_name }}-runtime-cuda12-windows.zip ../../../; cd ../../../
          certutil -hashfile ${{ steps.get_version.outputs.tag_name }}-runtime-cuda12-windows.zip MD5 > ${{ steps.get_version.outputs.tag_name }}-runtime-cuda12-windows.zip.md5

      - name: Generate Windows Download Information
        run: |
          cmake -D OUTPUT_FILE=RELEASE_NOTES.md -P cmake/extractChangelog.cmake
          
          # jade tools slim runtime 信息
          $file_slim = "${{ steps.get_version.outputs.tag_name }}-runtime-slim-windows.zip"
          $md5_slim = Get-Content "$file_slim.md5" | Select-String -Pattern '[0-9a-f]{32}' | ForEach-Object { $_.Matches.Value }
          $download_url_slim = "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file_slim"
          # jade tools cpu runtime 信息
          $file_cpu = "${{ steps.get_version.outputs.tag_name }}-runtime-cpu-windows.zip"
          $md5_cpu = Get-Content "$file_cpu.md5" | Select-String -Pattern '[0-9a-f]{32}' | ForEach-Object { $_.Matches.Value }
          $download_url_cpu = "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file_cpu"
          # jade tools cuda runtime 信息
          $file_cuda_12 = "${{ steps.get_version.outputs.tag_name }}-runtime-cuda12-windows.zip"
          $md5_cuda_12 = Get-Content "$file_cuda_12.md5" | Select-String -Pattern '[0-9a-f]{32}' | ForEach-Object { $_.Matches.Value }
          $download_url_cuda_12 = "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.tag_name }}/$file_cuda_12"
          $json = @{
            platform = "windows"
            tag_name = "${{ steps.get_version.outputs.tag_name }}"
            packages = @(
              @{name="slim"; file = $file_slim; md5 = $md5_slim; download_url = $download_url_slim },
              @{name="cpu"; file = $file_cpu; md5 = $md5_cpu; download_url = $download_url_cpu },
              @{name="cuda12"; file = $file_cuda_12; md5 = $md5_cuda_12; download_url = $download_url_cuda_12 }
            )
          }
          $json | ConvertTo-Json -Depth 3 | Out-File -FilePath windows.json -Encoding utf8
          

      - name: Upload Windows Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: "${{ steps.get_version.outputs.tag_name }}"
          body_path: "RELEASE_NOTES.md"
          files: |
            ${{ steps.get_version.outputs.tag_name }}-slim-windows.zip
            ${{ steps.get_version.outputs.tag_name }}-cpu-windows.zip
            ${{ steps.get_version.outputs.tag_name }}-cuda12-windows.zip
            ${{ steps.get_version.outputs.tag_name }}-runtime-slim-windows.zip
            ${{ steps.get_version.outputs.tag_name }}-runtime-cpu-windows.zip
            ${{ steps.get_version.outputs.tag_name }}-runtime-cuda12-windows.zip
            windows.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}